camera:
- counting:
    online: false
    params: []
  heatMap:
    online: false
    params: []
  hesitate:
    online: false
    params: []
- counting:
    online: false
    params: []
  heatMap:
    online: false
    params: []
  hesitate:
    online: false
    params: []
- counting:
    online: false
    params: []
  heatMap:
    online: false
    params: []
  hesitate:
    online: false
    params: []
