camera:
- counting:
    online: false
    params: []
  heatMap:
    online: true
    params:
    - parmasToken: '1598198732000'
      polygon:
      - x: 0.09
        y: 0.4
      - x: 0.37
        y: 0.31
      - x: 0.79
        y: 0.41
      - x: 0.76
        y: 0.97
      - x: 0.18
        y: 0.96
      - x: 0.09
        y: 0.4
  hesitate:
    online: false
    params: []
- counting:
    online: true
    params:
    - direction:
      - x: 0.65
        y: 0.52
      - x: 0.95
        y: 0.68
      line:
      - x: 0.93
        y: 0.22
      - x: 0.88
        y: 0.66
      - x: 0.63
        y: 0.9
      parmasToken: '1598198748000'
      polygon:
      - x: 0.73
        y: 0.27
      - x: 0.99
        y: 0.41
      - x: 0.99
        y: 0.96
      - x: 0.54
        y: 0.63
      - x: 0.61
        y: 0.36
      - x: 0.73
        y: 0.27
  heatMap:
    online: false
    params: []
  hesitate:
    online: false
    params: []
- counting:
    online: false
    params: []
  heatMap:
    online: false
    params: []
  hesitate:
    online: true
    params:
    - duration: 10
      parmasToken: '1598198760000'
      polygon:
      - x: 0.4
        y: 0.5
      - x: 0.73
        y: 0.69
      - x: 0.55
        y: 1
      - x: 0.22
        y: 0.99
      - x: 0.14
        y: 0.72
      - x: 0.4
        y: 0.5
